from pathlib import Path
import sys

import pandas as pd
import plotly.express as px
import streamlit as st

APP_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = APP_DIR.parent

sys.path.append(str(PROJECT_ROOT))
sys.path.append(str(APP_DIR))

from components.ui_styles import apply_custom_style


st.set_page_config(
    page_title="AI-Doctor Agreement Analytics | OrthoVision AI",
    page_icon="🤝",
    layout="wide",
)

apply_custom_style()


REQUIRED_COLUMNS = [
    "timestamp",
    "report_id",
    "patient_id",
    "body_region",
    "model_name",
    "ai_prediction",
    "confidence",
    "risk_level",
    "doctor_name",
    "doctor_specialization",
    "doctor_shift",
    "doctor_review_time",
    "doctor_feedback",
    "doctor_notes",
]


def find_feedback_file():
    """
    Priority:
    1. Real runtime feedback CSV generated by Doctor Review Mode.
    2. Demo sample CSV kept in assets for deployed showcase.
    """
    real_feedback = APP_DIR / "feedback" / "doctor_feedback.csv"
    sample_feedback = APP_DIR / "assets" / "sample_doctor_feedback.csv"

    if real_feedback.exists() and real_feedback.stat().st_size > 0:
        return real_feedback, "Live doctor feedback data"

    if sample_feedback.exists() and sample_feedback.stat().st_size > 0:
        return sample_feedback, "Demo sample feedback data"

    return None, None


@st.cache_data(show_spinner=False)
def load_feedback_data(file_path):
    df = pd.read_csv(file_path)

    for col in REQUIRED_COLUMNS:
        if col not in df.columns:
            df[col] = ""

    df = df[REQUIRED_COLUMNS].copy()

    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df["confidence"] = pd.to_numeric(df["confidence"], errors="coerce").fillna(0)

    text_cols = [
        "report_id",
        "patient_id",
        "body_region",
        "model_name",
        "ai_prediction",
        "risk_level",
        "doctor_name",
        "doctor_specialization",
        "doctor_shift",
        "doctor_review_time",
        "doctor_feedback",
        "doctor_notes",
    ]

    for col in text_cols:
        df[col] = df[col].fillna("Not provided").astype(str)

    df["doctor_feedback_clean"] = df["doctor_feedback"].str.strip().str.lower()
    df["ai_prediction_clean"] = df["ai_prediction"].str.strip().str.lower()

    df["agreement_bucket"] = df["doctor_feedback_clean"].map({
        "agree": "Agreed",
        "disagree": "Disagreed",
        "needs review": "Needs Review",
    }).fillna("Other")

    return df


def apply_filters(df):
    with st.sidebar:
        st.markdown("### Analytics Filters")

        view_mode = st.radio(
            "Counting Mode",
            ["Latest review per Report ID", "All feedback rows"],
            index=0,
        )

        body_regions = sorted([x for x in df["body_region"].dropna().unique() if x])
        selected_regions = st.multiselect(
            "Body Region",
            body_regions,
            default=body_regions,
        )

        feedback_options = sorted([x for x in df["agreement_bucket"].dropna().unique() if x])
        selected_feedback = st.multiselect(
            "Doctor Feedback",
            feedback_options,
            default=feedback_options,
        )

        prediction_options = sorted([x for x in df["ai_prediction"].dropna().unique() if x])
        selected_predictions = st.multiselect(
            "AI Prediction",
            prediction_options,
            default=prediction_options,
        )

    filtered = df.copy()

    if selected_regions:
        filtered = filtered[filtered["body_region"].isin(selected_regions)]

    if selected_feedback:
        filtered = filtered[filtered["agreement_bucket"].isin(selected_feedback)]

    if selected_predictions:
        filtered = filtered[filtered["ai_prediction"].isin(selected_predictions)]

    if view_mode == "Latest review per Report ID":
        filtered = (
            filtered.sort_values("timestamp")
            .drop_duplicates(subset=["report_id"], keep="last")
            .copy()
        )

    return filtered, view_mode


def metric_card(label, value, caption):
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-title">{label}</div>
            <div class="metric-value">{value}</div>
            <div class="metric-caption">{caption}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def percentage(part, total):
    if total <= 0:
        return 0.0
    return round((part / total) * 100, 2)


def build_kpis(df):
    total = len(df)
    agreed = int((df["agreement_bucket"] == "Agreed").sum())
    disagreed = int((df["agreement_bucket"] == "Disagreed").sum())
    needs_review = int((df["agreement_bucket"] == "Needs Review").sum())
    agreement_rate = percentage(agreed, total)
    avg_confidence = round(df["confidence"].mean(), 2) if total else 0

    return {
        "total": total,
        "agreed": agreed,
        "disagreed": disagreed,
        "needs_review": needs_review,
        "agreement_rate": agreement_rate,
        "avg_confidence": avg_confidence,
    }


def render_empty_state():
    st.warning(
        "No doctor feedback data found. Add feedback from AI Scan Room or place "
        "`sample_doctor_feedback.csv` inside `app/assets/`."
    )


st.markdown(
    """
    <div class="hero-card">
        <div class="hero-title">🤝 AI-Doctor Agreement Analytics</div>
        <div class="hero-subtitle">
            Analyze how often AI predictions match doctor reviews using human-in-the-loop feedback.
            This dashboard improves credibility by measuring expert agreement, disagreement, uncertainty,
            and confidence patterns.
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

feedback_file, data_label = find_feedback_file()

if feedback_file is None:
    render_empty_state()
    st.stop()

df = load_feedback_data(str(feedback_file))

if df.empty:
    render_empty_state()
    st.stop()

filtered_df, view_mode = apply_filters(df)
kpis = build_kpis(filtered_df)

st.caption(f"Data source: {data_label} | File: {feedback_file.name} | Mode: {view_mode}")

k1, k2, k3, k4, k5 = st.columns(5)

with k1:
    metric_card("Total Reviewed Cases", kpis["total"], "Doctor feedback records analyzed")

with k2:
    metric_card(
        "Doctor Agreed",
        f'{kpis["agreed"]} ({percentage(kpis["agreed"], kpis["total"])}%)',
        "AI prediction matched expert review",
    )

with k3:
    metric_card(
        "Doctor Disagreed",
        f'{kpis["disagreed"]} ({percentage(kpis["disagreed"], kpis["total"])}%)',
        "AI prediction did not match expert review",
    )

with k4:
    metric_card(
        "Needs Review",
        f'{kpis["needs_review"]} ({percentage(kpis["needs_review"], kpis["total"])}%)',
        "Uncertain or pending expert decision",
    )

with k5:
    metric_card(
        "Agreement Rate",
        f'{kpis["agreement_rate"]}%',
        f'Average AI confidence: {kpis["avg_confidence"]}%',
    )

st.markdown("")

if filtered_df.empty:
    st.warning("No records matched the selected filters.")
    st.stop()

chart_col1, chart_col2 = st.columns([1, 1])

with chart_col1:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("Agreement Distribution")

    distribution = (
        filtered_df["agreement_bucket"]
        .value_counts()
        .rename_axis("Doctor Feedback")
        .reset_index(name="Cases")
    )

    fig_distribution = px.pie(
        distribution,
        names="Doctor Feedback",
        values="Cases",
        hole=0.55,
    )
    fig_distribution.update_layout(
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=10, t=30, b=10),
        legend_title_text="Feedback",
    )
    st.plotly_chart(fig_distribution, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

with chart_col2:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("AI Prediction vs Doctor Feedback")

    pred_feedback = (
        filtered_df.groupby(["ai_prediction", "agreement_bucket"])
        .size()
        .reset_index(name="Cases")
    )

    fig_pred_feedback = px.bar(
        pred_feedback,
        x="ai_prediction",
        y="Cases",
        color="agreement_bucket",
        barmode="group",
        labels={
            "ai_prediction": "AI Prediction",
            "agreement_bucket": "Doctor Feedback",
        },
    )
    fig_pred_feedback.update_layout(
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=10, t=30, b=10),
    )
    st.plotly_chart(fig_pred_feedback, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

chart_col3, chart_col4 = st.columns([1, 1])

with chart_col3:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("Average AI Confidence by Doctor Decision")

    confidence_feedback = (
        filtered_df.groupby("agreement_bucket")["confidence"]
        .mean()
        .reset_index(name="Average Confidence")
    )

    fig_conf = px.bar(
        confidence_feedback,
        x="agreement_bucket",
        y="Average Confidence",
        text="Average Confidence",
        labels={
            "agreement_bucket": "Doctor Feedback",
            "Average Confidence": "Average AI Confidence (%)",
        },
    )
    fig_conf.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
    fig_conf.update_layout(
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=10, t=30, b=10),
        yaxis_range=[0, 100],
    )
    st.plotly_chart(fig_conf, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

with chart_col4:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("Region-wise Reviewed Cases")

    region_summary = (
        filtered_df.groupby(["body_region", "agreement_bucket"])
        .size()
        .reset_index(name="Cases")
    )

    fig_region = px.bar(
        region_summary,
        x="body_region",
        y="Cases",
        color="agreement_bucket",
        barmode="stack",
        labels={
            "body_region": "Body Region",
            "agreement_bucket": "Doctor Feedback",
        },
    )
    fig_region.update_layout(
        template="plotly_dark",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=10, r=10, t=30, b=10),
    )
    st.plotly_chart(fig_region, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

st.markdown('<div class="section-card">', unsafe_allow_html=True)
st.subheader("Recent Reviewed Cases")

recent_cols = [
    "timestamp",
    "report_id",
    "patient_id",
    "body_region",
    "ai_prediction",
    "confidence",
    "risk_level",
    "doctor_name",
    "doctor_specialization",
    "doctor_feedback",
    "doctor_notes",
]

recent_df = filtered_df.sort_values("timestamp", ascending=False)[recent_cols].copy()
recent_df["timestamp"] = recent_df["timestamp"].dt.strftime("%Y-%m-%d %H:%M:%S")
recent_df["confidence"] = recent_df["confidence"].map(lambda x: f"{x:.2f}%")

st.dataframe(
    recent_df,
    use_container_width=True,
    hide_index=True,
)

csv_data = recent_df.to_csv(index=False).encode("utf-8")
st.download_button(
    "Download Analytics CSV",
    data=csv_data,
    file_name="ai_doctor_agreement_analytics.csv",
    mime="text/csv",
)

st.markdown("</div>", unsafe_allow_html=True)

st.markdown(
    """
    <div class="section-card">
        <h3>Research Interpretation</h3>
        <p>
            A high AI-doctor agreement rate suggests that the model predictions are generally aligned
            with expert review. Disagreement and Needs Review cases are especially valuable because
            they identify difficult cases for future model improvement, dataset refinement, and
            clinical validation.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)
